import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { useRoadmap } from '../store'
import { elapsedAcrossSessions, isOverTwoX } from '../lib/timer'
import { PageTitle, Panel } from '../components/shared'

export default function Analytics() {
 const { tasks, timerSessions } = useRoadmap(); const rows = tasks.map(t => ({ task: t, actual: elapsedAcrossSessions(timerSessions, t.id) / 3600000 }));
 const by = (key: 'group'|'topic') => Object.entries(rows.reduce<Record<string, number>>((a, r) => (a[r.task[key]] = (a[r.task[key]] ?? 0) + r.actual, a), {}))
 const days = useMemo(() => Array.from({length:14}, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 13 + i); const key = d.toISOString().slice(0,10); const h = timerSessions.reduce((sum,s) => { const start = Date.parse(s.startedAt), end = Date.parse(s.endedAt ?? new Date().toISOString()); return sum + (new Date(start).toISOString().slice(0,10) === key ? Math.max(0,end-start)/3600000 : 0) },0); return {key,h} }), [timerSessions]);
 const sections = (title:string, field:'group'|'topic', entries:[string,number][]) => <Panel title={title}><div className="analytics-table"><div><b>Name</b><b>Estimate</b><b>Actual</b><b>Accuracy</b></div>{entries.map(([name,actual]) => { const estimate = rows.filter(r => r.task[field] === name).reduce((s,r)=>s+r.task.budgetHours,0); return <div key={name}><span>{name}</span><span>{estimate.toFixed(1)} h</span><span>{actual.toFixed(1)} h</span><span>{estimate ? `${Math.round(actual/estimate*100)}%` : '—'}</span></div> })}</div></Panel>
 return <><PageTitle eyebrow="TIME REPORT" title="Analytics" subtitle="Estimated and focused hours from saved timer sessions."/><div className="analytics-timer-grid"><Panel title="By step"><div className="analytics-table"><div><b>Step</b><b>Estimate</b><b>Actual</b><b>Accuracy</b></div>{rows.map(({task,actual})=><div key={task.id}><Link to={`/focus/${task.id}`}>{task.id} · {task.step}</Link><span>{task.budgetHours} h</span><span>{actual.toFixed(1)} h</span><span>{Math.round(actual/Math.max(task.budgetHours,0.01)*100)}%</span></div>)}</div></Panel>{sections('By group','group',by('group'))}{sections('By topic','topic',by('topic'))}<Panel title="Focused hours · last 14 days"><div className="day-bars">{days.map(d=><div key={d.key} title={`${d.key}: ${d.h.toFixed(2)} h`}><i style={{height:`${Math.min(d.h*16,160)}px`}}/><small>{d.key.slice(5)}</small></div>)}</div></Panel><Panel title="Steps over 2× budget">{rows.filter(r=>isOverTwoX(r.actual*3600000,r.task.budgetHours)).map(r=><div className="task-row" key={r.task.id}><Link to={`/focus/${r.task.id}`}>{r.task.id} · {r.task.step}</Link><span>{r.actual.toFixed(1)} / {r.task.budgetHours} h</span></div>)}{!rows.some(r=>isOverTwoX(r.actual*3600000,r.task.budgetHours))&&<p className="muted">No steps over twice their estimate.</p>}</Panel></div></>
}
